// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyT_gdrLByCzLJVdFXHBKazT00PUoeki8',
    appId: '1:201888557879:web:0748e593b2ef844c3b08b2',
    messagingSenderId: '201888557879',
    projectId: 'todolist-4df62',
    authDomain: 'todolist-4df62.firebaseapp.com',
    storageBucket: 'todolist-4df62.firebasestorage.app',
    measurementId: 'G-9F1BT1SXXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjAJDEFt709bZZ5L-Vcf_5K32QQVYxfxw',
    appId: '1:201888557879:android:d79ad032439f20093b08b2',
    messagingSenderId: '201888557879',
    projectId: 'todolist-4df62',
    storageBucket: 'todolist-4df62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2w0dolosOySnIZlrYb80VlqS5zOrMKI8',
    appId: '1:201888557879:ios:9e194e669fc6eb803b08b2',
    messagingSenderId: '201888557879',
    projectId: 'todolist-4df62',
    storageBucket: 'todolist-4df62.firebasestorage.app',
    iosBundleId: 'com.example.flutterBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2w0dolosOySnIZlrYb80VlqS5zOrMKI8',
    appId: '1:201888557879:ios:9e194e669fc6eb803b08b2',
    messagingSenderId: '201888557879',
    projectId: 'todolist-4df62',
    storageBucket: 'todolist-4df62.firebasestorage.app',
    iosBundleId: 'com.example.flutterBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyT_gdrLByCzLJVdFXHBKazT00PUoeki8',
    appId: '1:201888557879:web:c9fa14d35b6146233b08b2',
    messagingSenderId: '201888557879',
    projectId: 'todolist-4df62',
    authDomain: 'todolist-4df62.firebaseapp.com',
    storageBucket: 'todolist-4df62.firebasestorage.app',
    measurementId: 'G-EQ2BRS0KJ3',
  );
}
